spring:
  application.name: study-kotlin-liquibase
  profiles.active: dev
  liquibase:
    enabled: true
    user: "test_service_name_user"
    password: "secretpassword"
    url: "jdbc:postgresql://localhost:5433/postgres?currentSchema=test_service_name"
    change-log: "classpath:/db/changelog-master.yaml"

database:
  jdbcUrl: "jdbc:postgresql://localhost:5433/postgres?currentSchema=test_service_name"
  user: "test_service_name_app"
  password: "secretpassword"